---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: "os_update-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    # image: "${namespace:-ghcr.io/mullholland}/docker-molecule-${platform:-centos7}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ASYNC_DIR: /tmp/.ansible_async
verifier:
  name: ansible
