---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: "${scenario:-default}-${ansible:-latest}-${platform:-os_updates}"
    # image: "${namespace:-ghcr.io/buluma}/docker-molecule-images-${platform:-centos7}"
    image: "buluma/docker-molecule-images:${MOLECULE_DISTRO:-ubuntu2204}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ASYNC_DIR: /tmp/.ansible_async
verifier:
  name: ansible
